### ISSUE TITLE
Unused static member licenseCallback in LexActivator.cs, Line 1271

### ISSUE THREAD

**Issue by 2coder** [cryptlex/lexactivator-csharp#3]
The private static member licenseCallback in LexActivator.cs, Line 1271 is not used anywhere.

**Comment by adnan-kamili** [comment]
It is to prevent garbage collection of delegate, need to keep a reference

**Comment by 2coder** [comment]
Yes, but where do you assign it, as  there is no assignment to this variable.
So how would it keep the reference?

**Comment by adnan-kamili** [comment]
It is to prevent garbage collection of delegate, not the variable.
